#!/usr/bin/env bash
python3 task.py \
    --run_training="True" \
    --batch_size=32 \
    --epochs=25 \
    --change_lr_epoch=21 \
    --run_fine_tune="True" \
    --fine_tune_epochs=1 \
    --gpu_count=1 \
    --run_eval="True" \
    --val_set="val_set.csv" \
    --run_predict="True" \
    --new_model="True" \
    --model_name="InceptionV2Resnet" \
    --model_label="model" \
    --model_folder="models" \
    --train_folder="stage1_train" \
    --label_folder="stage1_labels" \
    --label_list="train.csv" \
    --predict_folder="stage1_test" \
    --submission_folder="stage1_submit" \
    --submission_list="sample_submission.csv" \
    --job_id=''
